config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  delete '/log-out' => 'sessions#destroy', as: :log_out

  resources :users do
    resources :questions
  end

  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :users
  belongs_to :questions
  validates :body, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  validates :title, :presence => true
  validates :body, :presence => true
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, uniqueness: true
  before_save :encrypt_password
  after_save :send_confirmation_mail
  has_many :questions
  has_many :answers

  def encrypt_password
    self.password_salt ||= BCrypt::Engine.generate_salt
    self.password_hash ||= BCrypt::Engine.hash_secret(password, password_salt)
  end

  def send_confirmation_mail
    UserMailer.signup_confirmation(self).deliver_now
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      return user
    else
      return nil
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @user = current_user
    @answer = @question.answers.new(answer_params)
    @user.answers.push(@answer)
    if @answer.save
      flash[:notice] = "Your answer has been added!"
    else
      flash[:notice] = "Uh oh. Something went wrong. Try again."
    end
    redirect_to user_question_path(@question.user, @question)
  end

  private
  def answer_params
    params.require(:answer).permit(:body, :user_id, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @questions = Question.all.sort_by{ |object| [object.created_at] }.reverse
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def show
    @question = Question.find(params[:id])
    @user = @question.user
    @answers = @question.answers
  end

  def new
    @question = Question.new
  end

  def create
    @user = User.find(params[:user_id])
    @question = @user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Question has been successfully added!"
      redirect_to "/"
    else
      flash[:notice] = "There was a problem posting your question. Try again."
      render :new
    end
  end

  private
  def question_params
    params.require(:question).permit(:title, :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    authorize @users
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Sign up success!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def update
    if params[:update_info] == "make_admin"
      authorize user = User.find(params[:id])
      user.update(:admin? => true)
      flash[:notice] = "#{user.email} was given admin status."
      redirect_to users_path
    end
  end

  def destroy
      authorize user = User.find(params[:id])
      user.destroy
      flash[:notice] = "#{user.email} has been deleted."
      redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading text-center">Stack Underflow</div>
  <div class="panel-body text-center">
      <% if current_user %>
        <%= link_to 'Add a New Question', new_user_question_path(current_user) %>
      <% else %>
        Please <%= link_to 'log in', log_in_path %> to post a question.
      <% end %>
  </div>

  <!-- List group -->
  <ul class="list-group">
    <% @questions.each do |question| %>
      <li class="list-group-item"><%= link_to question.title, user_question_path(question.user, question), :id => question.id %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_path %></li>
      <% if current_user %>
        <li class="navbar-right"><%= link_to current_user.email, user_path(current_user) %></li>
        <li><%= link_to 'Log Out', log_out_path, method: :delete %></li>
        <% if current_user.admin? %>
          <li> <%= link_to 'Admin Panel', users_path %> </li>
        <% end %>
      <% else %>
        <li><%= link_to 'Log In', log_in_path %></li>
        <li><%= link_to 'Sign Up', new_user_path %></li>
      <% end %>
    </ul>
  </nav>

  <div class="background">
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"> <%= flash[:notice] %> </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert"> <%= flash[:alert] %> </div>
      <% end %>

      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/questions/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center">New Question</div>
    <div class="panel-body">
    <%= bootstrap_form_for [current_user, @question] do |f| %>
      <%=f.text_field :title %>
      <%=f.text_area :body %>
    <%=f.submit "Submit Question" %>
  <%end%>
</div>
</div>

app/views/questions/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center"><%= @question.title %> asked by <%= @user.email %></div>
  <div class="panel-body">
    <%= @question.body %>
  </div>
  <ul class="list-group">
    <% @answers.each do |answer| %>
      <li class="list-group-item"> <b><%= User.find(answer.user_id).email %></b>: <%= answer.body %></li>
    <% end %>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading text-center">Add an Answer</div>
  <div class="panel-body">
      <%= bootstrap_form_for [@question, Answer.new] do |f| %>
          <%= f.text_area :body, hide_label: true, :rows => "5" %>
        <%= f.submit "Submit Answer", :class => 'btn btn-success' %>
      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.email %>
      <% if user.admin? %>
        <span> Admin </span>
      <% else %>
        <%= link_to "Make Admin", user_path(user, :update_info => "make_admin"), :method => "patch", :id => user.id %>
        <%= link_to "Delete User", user_path(user), :data => {:confirm => "Are you sure?",
										                                          :method => "delete"}, :id => "delete #{user.id}" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center">Sign Up</div>
    <div class="panel-body">
      <%= bootstrap_form_for @user do |f| %>
        <%=f.email_field :email %>
        <%=f.password_field :password %>
        <%=f.password_field :password_confirmation %>
      <%=f.submit "Sign Up", :id => 'new-user', :class => 'btn btn-success' %>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading text-center">Questions <%= @user.email %> has posted:</div>
  <ul class="list-group">
    <% @user.questions.each do |question| %>
      <li class="list-group-item"><%= link_to question.title, user_question_path(question.user, question), :id => question.id %></li>
    <% end %>
  </ul>
  </div>
</div>